# Screen, stage, and generate a reviewed migration wave in a disposable worktree.
# Adapted from dev/specmill-full/prepare.R and stage.R, with these differences:
# - lifecycle badges and @apiStage tags are copied from each original file, never downgraded;
# - stable files are regenerated by deleting them in the worktree (specmill >= 0.1.6 then owns them);
# - man/ and NAMESPACE must be unchanged after roxygen in the worktree.
# Usage (clean committed checkout): Rscript dev/specmill-rebuild/wave.R <wave-name> [name ...]
# Without names, every screened candidate is staged. Nothing in the working tree changes
# except dev/specmill-rebuild/screen-results.json.
args <- commandArgs(TRUE)
stopifnot(length(args) >= 1L)
wave <- args[[1]]
only <- args[-1]
`%||%` <- function(a, b) if (is.null(a)) b else a
source('dev/install_specmill.R')
verify_specmill()
root <- normalizePath('.')
baseline <- 'dev/specmill-pilot/artifacts/before-source'
stopifnot(dir.exists(baseline), length(system('git status --porcelain', intern = TRUE)) == 0L)
audit <- jsonlite::read_json('dev/specmill-pilot/all-schema-diagnostics.json')
operations <- Filter(function(x) !grepl('_prod[.]json$', x$schema), audit$operations)
inventory <- jsonlite::read_json('dev/specmill-rebuild/inventory.json')$definitions
pending <- Filter(function(d) identical(d$category, 'unmapped_wrapper'), inventory)
names(pending) <- vapply(pending, `[[`, '', 'name')
hooks <- names(yaml::read_yaml('inst/hook_config.yml'))
callbacks <- new.env(parent = baseenv())
sys.source('dev/specmill_callbacks.R', callbacks)
short_path <- function(key) sub('^/(api/)?', '', gsub('\\{[^}]+\\}', '', sub('^[A-Z]+ ', '', key)))
binding <- function(x, parameters) {
  if (is.symbol(x) && as.character(x) %in% parameters) {
    return(list(from = list('params', as.character(x))))
  }
  if (identical(x, quote(as.numeric(Sys.getenv('batch_limit', '100'))))) {
    return(list(callback = 'detail_batch_limit'))
  }
  if (is.call(x) || is.symbol(x)) {
    stop('Nonliteral helper argument needs manual mapping')
  }
  list(value = x)
}
allowed_tags <- c('@description', '@param', '@return', '@apiStage', '@export', '@examples', '@md')
documentation <- function(lines, start, name) {
  block <- lines[seq_len(start - 1L)]
  block <- tail(block, length(block) - max(c(0L, which(!grepl("^#'|^$|^# ", block)))))
  text <- sub("^#' ?", '', block[grepl("^#'", block)])
  tags <- regmatches(text, regexpr('^@[A-Za-z]+', text))
  if (any(!tags %in% allowed_tags)) {
    stop('Rich documentation needs manual mapping')
  }
  tag_rows <- grep('^@', text)
  desc_row <- which(text == '@description')
  if (length(desc_row) != 1L) {
    stop('Documentation without a single @description needs manual mapping')
  }
  desc <- text[seq.int(desc_row + 1L, min(tag_rows[tag_rows > desc_row], length(text) + 1L) - 1L)]
  badge <- regmatches(desc, regexpr('lifecycle::badge\\("[a-z]+"\\)', desc))
  if (length(badge) != 1L) {
    stop('Missing or multiple lifecycle badges need manual mapping')
  }
  prose <- desc[nzchar(desc) & !grepl('lifecycle::badge', desc, fixed = TRUE)]
  if (length(prose)) {
    stop('Description prose needs manual mapping')
  }
  if (sum(nzchar(text[seq_len(desc_row - 1L)])) != 1L) {
    stop('Multi-line title or details need manual mapping')
  }
  params <- grep('^@param ', text, value = TRUE)
  descriptions <- setNames(sub('^@param [^ ]+ ', '', params), sub('^@param ([^ ]+).*', '\\1', params))
  example <- text[seq.int(which(text == '@examples') + 1L, length(text))]
  example <- example[nzchar(example) & !example %in% c('\\dontrun{', '}')]
  calls <- parse(text = example)
  examples <- lapply(calls, function(call) {
    if (!is.call(call) || !identical(call[[1L]], as.name(name))) {
      stop('Custom example needs manual mapping')
    }
    args <- as.list(call)[-1L]
    if (!length(args)) {
      return(setNames(list(), character()))
    }
    lapply(args, function(x) {
      if (is.call(x) || is.symbol(x)) stop('Computed example needs manual mapping')
      x
    })
  })
  stopifnot(length(examples) > 0L)
  stage <- grep('^@apiStage ', text, value = TRUE)
  docs <- list(
    title = text[[1L]],
    lifecycle = sub('.*"([a-z]+)".*', '\\1', badge),
    parameters = as.list(descriptions),
    return = sub('^@return ', '', grep('^@return ', text, value = TRUE)),
    examples = examples
  )
  if (length(stage)) docs$tags <- list(apiStage = sub('^@apiStage ', '', stage))
  docs
}

# 1. Screen every pending wrapper; the first failing reason is recorded.
records <- list()
for (file in unique(vapply(pending, `[[`, '', 'file'))) {
  exprs <- parse(file, keep.source = TRUE)
  refs <- attr(exprs, 'srcref')
  lines <- readLines(file, warn = FALSE)
  for (i in seq_along(exprs)) {
    expr <- exprs[[i]]
    if (!is.call(expr) || !identical(expr[[1]], as.name('<-')) || !as.character(expr[[2]]) %in% names(pending)) {
      next
    }
    name <- as.character(expr[[2]])
    record <- list(name = name, file = file, status = 'retained', reason = '', schema = NULL, key = NULL)
    proposal <- tryCatch(
      {
        if (name %in% hooks) stop('Client hook policy requires manual review')
        fn <- eval(expr[[3]])
        code <- as.list(body(fn))[-1L]
        if (
          length(code) != 2L || !is.call(code[[1]]) || !identical(code[[1]][[1]], as.name('<-')) ||
            !identical(code[[1]][[2]], as.name('result')) || !identical(code[[2]], quote(return(result)))
        ) {
          stop('Custom implementation requires manual mapping')
        }
        call <- code[[1]][[3]]
        helper <- as.character(call[[1]])
        if (!helper %in% c('generic_request', 'generic_chemi_request')) stop('Helper outside schema migration scope')
        args <- as.list(call)[-1L]
        method <- args$method %||% if (helper == 'generic_chemi_request') 'POST' else 'GET'
        prefix <- if (startsWith(name, 'ct_')) 'ctx-' else if (startsWith(name, 'epi_')) 'epi-' else 'chemi-'
        matches <- Filter(function(op) {
          startsWith(op$key, paste0(method, ' ')) && identical(short_path(op$key), args$endpoint) &&
            startsWith(op$schema, prefix)
        }, operations)
        if (length(matches) != 1L) stop('No unique supported schema/method/path match; no route guessed')
        record$schema <- matches[[1L]]$schema
        record$key <- matches[[1L]]$key
        docs <- documentation(lines, refs[[i]][[1L]], name)
        formal_list <- as.list(formals(fn))
        inputs <- lapply(names(formal_list), function(parameter) {
          default <- formal_list[parameter]
          required <- identical(default, setNames(as.list(formals(function(x) NULL)), parameter))
          if (!required && (is.call(default[[1]]) || is.symbol(default[[1]]))) {
            stop('Computed default requires manual mapping')
          }
          value <- if (required) NULL else default[[1]]
          settings <- list(type = if (is.numeric(value)) 'numeric' else if (is.logical(value)) 'logical' else 'character')
          if (required) settings$required <- TRUE else settings['default'] <- list(value)
          settings$description <- docs$parameters[[parameter]]
          settings
        })
        names(inputs) <- if (length(formal_list)) names(formal_list) else character()
        list(
          name = name, file = file, helper = helper, implementation = 'generated', inputs = inputs,
          request = list(arguments = lapply(args, binding, parameters = names(inputs))), docs = docs
        )
      },
      error = identity
    )
    if (inherits(proposal, 'error')) {
      record$reason <- conditionMessage(proposal)
    } else {
      record$status <- 'candidate'
      record$proposal <- proposal
      record$original <- expr[[3]]
    }
    records[[name]] <- record
  }
}
# Whole-file ownership: every top-level definition must be a candidate.
file_ready <- function(file) {
  selected <- names(Filter(function(x) x$file == file, records))
  length(parse(file)) == length(selected) && all(vapply(records[selected], function(x) x$status == 'candidate', FALSE))
}
for (file in unique(vapply(records, `[[`, '', 'file'))) {
  if (!file_ready(file)) {
    for (name in names(Filter(function(x) x$file == file && x$status == 'candidate', records))) {
      records[[name]]$status <- 'retained'
      records[[name]]$reason <- 'Inseparable grouped file contains a retained or unaccounted definition'
    }
  }
}

# 2. Render each candidate and compare formals and the helper-call boundary with the original.
contracts <- cases <- list()
Sys.setenv(batch_limit = '2')
for (name in names(Filter(function(x) x$status == 'candidate', records))) {
  record <- records[[name]]
  checked <- tryCatch(
    {
      out <- file.path('dev/specmill-pilot/artifacts/wave-review', name)
      dir.create(out, recursive = TRUE, showWarnings = FALSE)
      config <- list(
        id = 'review', schemas = list(files = list(file.path('schema', record$schema))),
        selection = list(include = list(record$key)), helper = record$proposal$helper,
        documentation = TRUE, operations = setNames(list(record$proposal), record$key)
      )
      yaml::write_yaml(config, file.path(out, 'review.yml'))
      yaml::write_yaml(
        list(config_version = 1L, package = 'ComptoxR', services = list(file.path(out, 'review.yml'))),
        file.path(out, 'project.yml')
      )
      project <- specmill::load_project('.', config = file.path(out, 'project.yml'), callbacks = callbacks)
      native <- specmill::read_operations(file.path('schema', record$schema), policy = project$services[[1L]]$policy)
      stopifnot(length(native$operations) == 1L, length(native$diagnostics) == 0L)
      mapped <- specmill:::configure_operation(native$operations[[1L]], project$services[[1L]])
      code <- specmill::render_operation(mapped$operation, mapped$spec)
      original <- eval(record$original, envir = new.env(parent = baseenv()))
      required <- names(Filter(function(x) isTRUE(x$required), record$proposal$inputs))
      supplied <- setNames(as.list(rep('pilot-1', length(required))), required)
      calls <- list()
      helper <- record$proposal$helper
      assign(helper, function(...) {
        calls[[length(calls) + 1L]] <<- list(helper = helper, arguments = list(...), response = list(list(id = 'pilot-response')))
        list(list(id = 'pilot-response'))
      }, envir = environment(original))
      result <- do.call(original, supplied)
      stopifnot(length(calls) == 1L)
      expected_calls <- calls
      env <- new.env(parent = environment(original))
      eval(parse(text = code), env)
      stopifnot(identical(formals(original), formals(env[[name]])))
      calls <- list()
      stopifnot(identical(do.call(env[[name]], supplied), result), identical(calls, expected_calls))
      stopifnot(identical(readLines(record$file), readLines(file.path(baseline, record$file))))
      contracts[[name]] <- list(inputs = supplied, calls = expected_calls, result = result, environment = list(batch_limit = '2'))
      cases[[name]] <- list(
        schema = record$schema, key = record$key, inputs = supplied, arguments = expected_calls[[1L]]$arguments,
        helper = helper, required = as.list(required)
      )
      code
    },
    error = identity
  )
  if (inherits(checked, 'error')) {
    records[[name]]$status <- 'retained'
    records[[name]]$reason <- paste('Candidate rejected:', conditionMessage(checked))
  }
}
for (file in unique(vapply(records, `[[`, '', 'file'))) {
  if (!file_ready(file)) {
    for (name in names(Filter(function(x) x$file == file && x$status == 'candidate', records))) {
      records[[name]]$status <- 'retained'
      records[[name]]$reason <- 'Grouped sibling failed candidate verification'
    }
  }
}
jsonlite::write_json(
  lapply(records, function(x) c(x[c('name', 'file', 'status', 'reason', 'schema', 'key')], lifecycle = x$proposal$docs$lifecycle)),
  'dev/specmill-rebuild/screen-results.json', pretty = TRUE, auto_unbox = TRUE, null = 'null'
)
candidates <- Filter(function(x) x$status == 'candidate', records)
if (length(only)) {
  stopifnot(all(only %in% names(candidates)))
  candidates <- candidates[only]
  stopifnot(all(vapply(unique(vapply(candidates, `[[`, '', 'file')), function(f) {
    all(names(Filter(function(x) x$file == f, records)) %in% only)
  }, FALSE)))
}
cat('Screened', length(records), 'wrappers;', sum(vapply(records, function(x) x$status == 'candidate', FALSE)), 'candidates;', length(candidates), 'staged\n')
print(table(vapply(records, `[[`, '', 'reason')))
if (!length(candidates)) quit(status = 0)

# 3. Stage in a disposable worktree: extend service mappings and fixtures, delete the
# candidate files, regenerate, and check documentation output.
commit <- system('git rev-parse HEAD', intern = TRUE)
work <- file.path(root, 'dev/specmill-pilot/artifacts', paste0('wave-', wave))
if (dir.exists(work)) system(sprintf('git worktree remove --force %s', shQuote(work)))
stopifnot(system(sprintf('git worktree add --detach %s %s', shQuote(work), commit)) == 0L)
dir.create(file.path(work, 'dev/specmill-pilot/artifacts'), recursive = TRUE)
file.symlink(file.path(root, 'dev/specmill-pilot/artifacts/toolkit-library'), file.path(work, 'dev/specmill-pilot/artifacts/toolkit-library'))
# The local roxygen may already differ from committed man/, so compare roxygen
# output of the generated worktree with roxygen output of its baseline.
roxygenise <- function() {
  stopifnot(system(sprintf("cd %s && Rscript -e 'roxygen2::roxygenise(roclets = c(\"rd\", \"namespace\"))' > /dev/null 2>&1", shQuote(work))) == 0L)
  docs <- c(file.path(work, 'NAMESPACE'), list.files(file.path(work, 'man'), pattern = '[.]Rd$', full.names = TRUE))
  hashes <- setNames(vapply(docs, digest::digest, '', file = TRUE, algo = 'sha256'), basename(docs))
  stopifnot(system(sprintf('cd %s && git checkout -- man NAMESPACE DESCRIPTION && git clean -fdq man', shQuote(work))) == 0L)
  hashes
}
docs_before <- roxygenise()
fixture <- 'tests/testthat/fixtures/specmill-rebuild-contracts.rds'
all_contracts <- if (file.exists(fixture)) readRDS(fixture) else list()
all_contracts[names(candidates)] <- contracts[names(candidates)]
saveRDS(all_contracts[sort(names(all_contracts))], file.path(work, fixture), version = 3)
case_file <- 'dev/specmill-rebuild/runtime-cases.rds'
all_cases <- if (file.exists(case_file)) readRDS(case_file) else list()
all_cases[names(candidates)] <- cases[names(candidates)]
saveRDS(all_cases[sort(names(all_cases))], file.path(work, case_file), version = 3)
project <- yaml::read_yaml('specmill.yml')
project$callback_files <- as.list(project$callback_files)
project$services <- as.list(project$services)
for (schema in unique(vapply(candidates, `[[`, '', 'schema'))) {
  selected <- Filter(function(x) identical(x$schema, schema), candidates)
  id <- sub('[.]json$', '-rebuild', schema)
  path <- file.path('apis', paste0(id, '.yml'))
  service <- if (file.exists(path)) {
    yaml::read_yaml(path)
  } else {
    project$services <- c(project$services, list(path))
    list(
      id = id, schemas = list(files = list(file.path('schema', schema))), selection = list(include = list()),
      helper = 'generic_request', documentation = TRUE, operations = list(), contracts_file = fixture
    )
  }
  keys <- vapply(selected, `[[`, '', 'key')
  service$selection$include <- as.list(sort(unique(c(unlist(service$selection$include), keys))))
  service$operations[keys] <- lapply(selected, `[[`, 'proposal')
  service$operations <- service$operations[sort(names(service$operations))]
  yaml::write_yaml(service, file.path(work, path))
}
yaml::write_yaml(project, file.path(work, 'specmill.yml'))
files <- unique(vapply(candidates, `[[`, '', 'file'))
stopifnot(all(file.remove(file.path(work, files))))
generate <- function(mode) system(sprintf('cd %s && Rscript dev/generate_specmill.R --%s', shQuote(work), mode))
stopifnot(generate('apply') == 0L, generate('apply') == 0L, generate('check') == 0L)
docs_after <- roxygenise()
changed <- system(sprintf('cd %s && git status --porcelain', shQuote(work)), intern = TRUE)
if (!identical(docs_before, docs_after)) {
  print(names(docs_after)[docs_after != docs_before[names(docs_after)]])
  stop('Generated wrappers change documentation; worktree kept at ', work)
}
jsonlite::write_json(
  list(
    wave = wave, base_commit = commit, worktree = work, toolkit = jsonlite::read_json('dev/specmill-lock.json'),
    operations = length(candidates), files = as.list(files), changed = as.list(changed)
  ),
  file.path(work, 'dev/specmill-rebuild', paste0('wave-', wave, '.json')), pretty = TRUE, auto_unbox = TRUE
)
cat('Staged', length(candidates), 'operations in', length(files), 'files at', work, '\n')
