---
title: "ComptoxR: An R Package to Retrieve Compound Information from US EPA Products and APIs for Rapid Chemical Hazard, Risk, Toxicological Evaluation and Screening"

authors:
  - name: Sean Thimons
    affiliations: 
    - ref: orise
    orcid: 0000-0002-3736-2529
    corresponding: true
    email: thimons.sean@epa.gov
  - name: Grace Patlewicz
    affiliations: 
    - ref: epa
    orcid: 0000-0003-3863-9689
  - name: Antony Williams
    affiliations: 
    - ref: epa
    orcid: 0000-0002-2668-4821
  
affiliations:
  - id: orise
    name: Oak Ridge Institute for Science Education
    city: Oak Ridge
    state: TN
    country: USA
  - id: epa
    name: U.S. Environmental Protection Agency, Office of Research & Development, Center for Computational Toxicology & Exposure (CCTE)
    city: Research Triangle Park
    state: NC 
    country: USA

filters:
  - authors-block
        
prefer-html: true

format:
  #native: default
  docx: default
  html: default
  pdf:
    keep-tex: true
  
editor: visual
execute: 
  keep-md: false
  warning: false
  error: false
  message: false
  cache: true
editor_options: 
  chunk_output_type: inline
---

```{r}
#| include: false
#| label: tbl-cars
#| tbl-cap: "Head of cars data"


library(knitr)
kable(head(cars))

```

```{r}
#| include: false
#| label: tbl-pressure
#| tbl-cap: "Head of aqi data"

kable(head(pressure))

```



Look at @tbl-cars

Look at @tbl-pressure
