wrapmaint::bind_tools("test_helpers", environment())
# Configuration and small helpers for generated wrapper contract tests.

tg_config <- list(
  package_name = "ComptoxR",
  generated_header = "# Generated by dev/generate_tests.R; do not edit by hand.",
  legacy_metadata_header = "# Generated using metadata-based test generator",
  helper_names = c(
    "generic_request",
    "generic_chemi_request",
    "generic_pubchem_request"
  ),
  resolver_helper_names = c(
    "chemi_resolver_lookup",
    "chemi_resolver_lookup_bulk"
  ),
  test_dir = file.path("tests", "testthat")
)


tg_write_github_outputs <- function(values) {
  output <- Sys.getenv("GITHUB_OUTPUT")
  if (!nzchar(output)) {
    return(invisible(FALSE))
  }

  for (name in names(values)) {
    cat(sprintf("%s=%s\n", name, values[[name]]), file = output, append = TRUE)
  }

  invisible(TRUE)
}
