# Configuration and small helpers for generated wrapper contract tests.

`%tg||%` <- function(x, y) {
  if (is.null(x)) {
    y
  } else {
    x
  }
}

tg_config <- list(
  package_name = "ComptoxR",
  generated_header = "# Generated by dev/generate_tests.R; do not edit by hand.",
  legacy_metadata_header = "# Generated using metadata-based test generator",
  helper_names = c(
    "generic_request",
    "generic_chemi_request",
    "generic_cc_request",
    "generic_cts_request",
    "generic_pubchem_request"
  ),
  resolver_helper_names = c(
    "chemi_resolver_lookup",
    "chemi_resolver_lookup_bulk"
  ),
  test_dir = file.path("tests", "testthat")
)

tg_norm_path <- function(path) {
  normalizePath(path, winslash = "/", mustWork = FALSE)
}

tg_rel_path <- function(path, root = ".") {
  root <- tg_norm_path(root)
  path <- tg_norm_path(path)
  sub(paste0("^", gsub("([][{}()+*^$|\\\\.?])", "\\\\\\1", root), "/?"), "", path, perl = TRUE)
}

tg_file_path <- function(root, ...) {
  file.path(root, ...)
}

tg_read_lines <- function(path) {
  if (!file.exists(path)) {
    return(character(0))
  }
  readLines(path, warn = FALSE)
}

tg_read_text <- function(path) {
  paste(tg_read_lines(path), collapse = "\n")
}

tg_without_terminal_newline <- function(text) {
  sub("\\n\\z", "", text, perl = TRUE)
}

tg_generated_text_identical <- function(current, expected) {
  identical(tg_without_terminal_newline(current), tg_without_terminal_newline(expected))
}

tg_text_header_lines <- function(text, n = 5L) {
  lines <- strsplit(text, "\n", fixed = TRUE)[[1]]
  if (length(lines) == 0) {
    return(character(0))
  }
  lines[seq_len(min(n, length(lines)))]
}

tg_has_generated_header <- function(text) {
  tg_config$generated_header %in% tg_text_header_lines(text)
}

tg_has_legacy_metadata_header <- function(text) {
  tg_config$legacy_metadata_header %in% tg_text_header_lines(text)
}

tg_test_file_for <- function(function_name, root = ".") {
  tg_file_path(root, tg_config$test_dir, paste0("test-", function_name, ".R"))
}

tg_write_github_outputs <- function(values) {
  output <- Sys.getenv("GITHUB_OUTPUT")
  if (!nzchar(output)) {
    return(invisible(FALSE))
  }

  for (name in names(values)) {
    cat(sprintf("%s=%s\n", name, values[[name]]), file = output, append = TRUE)
  }

  invisible(TRUE)
}

tg_cli_info <- function(...) {
  if (requireNamespace("cli", quietly = TRUE)) {
    cli::cli_alert_info(...)
  } else {
    message(sprintf(...))
  }
}

tg_cli_success <- function(...) {
  if (requireNamespace("cli", quietly = TRUE)) {
    cli::cli_alert_success(...)
  } else {
    message(sprintf(...))
  }
}

tg_cli_warning <- function(...) {
  if (requireNamespace("cli", quietly = TRUE)) {
    cli::cli_alert_warning(...)
  } else {
    warning(sprintf(...), call. = FALSE)
  }
}

tg_cli_abort <- function(message) {
  if (requireNamespace("cli", quietly = TRUE)) {
    cli::cli_abort(message)
  } else {
    stop(paste(unlist(message), collapse = "\n"), call. = FALSE)
  }
}
