#!/usr/bin/env Rscript
# Test Gap Detection - Identify API wrapper functions without proper tests
#
# This script scans exported API wrapper functions that call generic request helpers
# and identifies which ones:
# - Have no test file at all (no_test_file)
# - Have an empty test file with no test_that() blocks (empty_test_file)
#
# Output:
# - JSON report to dev/reports/test_gaps_{YYYYMMDD}.json
# - GITHUB_OUTPUT variables (gaps_found, gaps_count) when in CI
# - CLI summary to stdout
#
# dev/test_manifest.json is retired and should normally be absent. It is not
# used as an authority for readiness counts or gap suppression. Use
# dev/unit_test_readiness_audit.R for the canonical read-only inventory.

library(cli)
library(fs)
library(jsonlite)
library(here)

source(file.path("dev", "test_generation", "00_config.R"))
source(file.path("dev", "test_generation", "01_inventory.R"))
source(file.path("dev", "test_generation", "02_wrapper_metadata.R"))

#' Read retired test manifest status
#'
#' @description
#' Returns a retired status object. If a legacy dev/test_manifest.json file is
#' present, it is read only for report context and is never authoritative.
#'
#' @return List with version, updated, and files fields
#' @export
read_test_manifest <- function() {
  manifest_path <- here::here("dev", "test_manifest.json")

  if (!file.exists(manifest_path)) {
    return(list(
      artifact_schema = "test_manifest_retired/v1",
      retired = TRUE,
      authority = FALSE,
      replacement = "dev/reports/unit_test_readiness_audit.json",
      exists = FALSE,
      files = list()
    ))
  }

  tryCatch({
    manifest <- jsonlite::fromJSON(manifest_path, simplifyVector = FALSE)
    manifest$exists <- TRUE
    manifest
  }, error = function(e) {
    cli::cli_alert_warning("Error reading manifest: {e$message}, using default")
    list(
      artifact_schema = "test_manifest_retired/v1",
      retired = TRUE,
      authority = FALSE,
      replacement = "dev/reports/unit_test_readiness_audit.json",
      exists = TRUE,
      files = list()
    )
  })
}

#' Write test manifest
#'
#' @description
#' Retained only to give callers an explicit retirement error. The manifest is
#' no longer generated by this detector.
#'
#' @param manifest List with version, updated, and files fields
#' @export
write_test_manifest <- function(manifest) {
  stop(
    "dev/test_manifest.json is retired. Use Rscript dev/unit_test_readiness_audit.R instead.",
    call. = FALSE
  )
}

#' Check if test file is protected
#'
#' @description
#' Legacy compatibility shim. The retired manifest no longer suppresses gap
#' detection, so no test file is considered protected by this detector.
#'
#' @param test_filename Test filename (e.g., "test-ct_hazard.R")
#' @param manifest Manifest structure from read_test_manifest()
#' @return Logical indicating protection status
#' @export
is_protected <- function(test_filename, manifest) {
  FALSE
}

#' Check if R file calls generic request functions
#'
#' @description
#' Uses parse() + all.names() to detect if a file calls:
#' - generic_request
#' - generic_chemi_request
#' - generic_cc_request
#' - generic_cts_request
#' - generic_pubchem_request
#'
#' @param file_path Path to R source file
#' @return Logical indicating if file calls generic request functions
#' @export
calls_generic_request <- function(file_path) {
  tryCatch({
    # Parse the R file
    exprs <- parse(file = file_path)

    # Extract all names (function calls) from all expressions
    all_names_in_file <- character(0)
    for (expr in exprs) {
      names_in_expr <- all.names(expr, functions = TRUE)
      all_names_in_file <- c(all_names_in_file, names_in_expr)
    }

    # Check if any generic request function is present
    generic_funcs <- tg_config$helper_names
    any(generic_funcs %in% all_names_in_file)

  }, error = function(e) {
    # If file can't be parsed, assume it doesn't call generic_request
    cli::cli_alert_warning("Could not parse {file_path}: {e$message}")
    FALSE
  })
}

#' Check if test file has real test_that() blocks
#'
#' @description
#' Reads test file and checks for test_that() function calls
#'
#' @param test_file_path Path to test file
#' @return Logical indicating if test file has test_that() blocks
#' @export
has_real_tests <- function(test_file_path) {
  if (!file.exists(test_file_path)) {
    return(FALSE)
  }

  tryCatch({
    lines <- readLines(test_file_path, warn = FALSE)
    any(grepl("test_that\\s*\\(", lines))
  }, error = function(e) {
    cli::cli_alert_warning("Could not read {test_file_path}: {e$message}")
    FALSE
  })
}

#' Detect stale protected entries in manifest
#'
#' @description
#' Checks if protected test files in the manifest:
#' - Still have corresponding R/ function files
#' - Still call generic_request functions
#'
#' @param manifest Manifest structure from read_test_manifest()
#' @return List of stale entries with reason
#' @export
detect_stale_protected <- function(manifest) {
  if (isTRUE(manifest$retired) || identical(manifest$authority, FALSE)) {
    return(list())
  }

  if (is.null(manifest$files) || length(manifest$files) == 0) {
    return(list())
  }

  stale <- list()

  for (test_filename in names(manifest$files)) {
    entry <- manifest$files[[test_filename]]

    # Only check protected files
    if (!isTRUE(entry$status == "protected")) {
      next
    }

    # Extract function name from test filename (test-ct_hazard.R -> ct_hazard)
    function_name <- sub("^test-", "", sub("\\.R$", "", test_filename))
    r_file <- here::here("R", paste0(function_name, ".R"))

    # Check if R file exists
    if (!file.exists(r_file)) {
      stale[[test_filename]] <- list(
        test_file = test_filename,
        reason = "r_file_missing",
        details = paste0("R file not found: ", r_file)
      )
      next
    }

    # Check if R file still calls generic_request
    if (!calls_generic_request(r_file)) {
      stale[[test_filename]] <- list(
        test_file = test_filename,
        reason = "not_api_wrapper",
        details = "R file no longer calls generic_request"
      )
    }
  }

  stale
}

#' Main gap detection function
#'
#' @description
#' Scans R/ for API wrapper functions, detects test gaps, writes report.
#'
#' @return List of gap objects (returned invisibly)
#' @export
detect_gaps <- function() {
  cli::cli_h1("Test Gap Detection")

  # Load retired manifest status for report context only.
  manifest <- read_test_manifest()
  if (isTRUE(manifest$retired) || identical(manifest$authority, FALSE)) {
    cli::cli_alert_info("dev/test_manifest.json is retired or absent; it will not suppress gaps.")
  }

  wrappers <- tg_collect_wrapper_metadata(here::here())

  cli::cli_alert_info("Scanning {length(wrappers)} exported API wrapper function{?s}...")

  gaps <- list()

  for (function_name in names(wrappers)) {
    wrapper <- wrappers[[function_name]]

    # Check for test file
    test_file <- here::here("tests", "testthat", paste0("test-", function_name, ".R"))
    test_filename <- paste0("test-", function_name, ".R")

    # The manifest is retired; this compatibility check always returns FALSE.
    if (is_protected(test_filename, manifest)) {
      # Skip protected files (they're manually maintained)
      next
    }

    # Detect gap conditions
    if (!file.exists(test_file)) {
      gaps[[function_name]] <- list(
        function_name = function_name,
        file_path = as.character(wrapper$file_path),
        test_file = as.character(test_file),
        reason = "no_test_file"
      )
    } else if (!has_real_tests(test_file)) {
      gaps[[function_name]] <- list(
        function_name = function_name,
        file_path = as.character(wrapper$file_path),
        test_file = as.character(test_file),
        reason = "empty_test_file"
      )
    }
  }

  # Check for stale protected entries
  stale <- detect_stale_protected(manifest)
  if (length(stale) > 0) {
    cli::cli_alert_warning("Found {length(stale)} stale protected entries in manifest")
    for (entry in stale) {
      cli::cli_alert_warning("  {entry$test_file}: {entry$details}")
    }
  }

  # Generate report
  timestamp <- format(Sys.time(), "%Y%m%d", tz = "UTC")
  report_dir <- here::here("dev", "reports")
  if (!dir.exists(report_dir)) {
    dir.create(report_dir, recursive = TRUE)
  }

  report_file <- file.path(report_dir, paste0("test_gaps_", timestamp, ".json"))

  # Write report
  report_data <- list(
    timestamp = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
    manifest_authoritative = FALSE,
    manifest_replacement = if (!is.null(manifest$replacement)) {
      manifest$replacement
    } else {
      "dev/reports/unit_test_readiness_audit.json"
    },
    gaps_count = length(gaps),
    gaps = gaps,
    stale_protected = stale
  )

  jsonlite::write_json(
    report_data,
    report_file,
    pretty = TRUE,
    auto_unbox = TRUE
  )

  cli::cli_alert_success("Report written: {report_file}")

  # Write GITHUB_OUTPUT if in CI
  if (Sys.getenv("GITHUB_OUTPUT") != "") {
    output_file <- Sys.getenv("GITHUB_OUTPUT")
    cat(sprintf("gaps_found=%s\n", ifelse(length(gaps) > 0, "true", "false")),
        file = output_file, append = TRUE)
    cat(sprintf("gaps_count=%d\n", length(gaps)),
        file = output_file, append = TRUE)
    cli::cli_alert_success("GITHUB_OUTPUT variables written")
  }

  # Print summary
  cli::cli_h2("Summary")
  cli::cli_alert_info("Total gaps found: {length(gaps)}")

  if (length(gaps) > 0) {
    # Group by reason
    no_test <- sum(sapply(gaps, function(x) x$reason == "no_test_file"))
    empty_test <- sum(sapply(gaps, function(x) x$reason == "empty_test_file"))

    if (no_test > 0) {
      cli::cli_alert_warning("Missing test files: {no_test}")
      for (gap in gaps) {
        if (gap$reason == "no_test_file") {
          cli::cli_text("  - {gap$function_name}")
        }
      }
    }

    if (empty_test > 0) {
      cli::cli_alert_warning("Empty test files: {empty_test}")
      for (gap in gaps) {
        if (gap$reason == "empty_test_file") {
          cli::cli_text("  - {gap$function_name}")
        }
      }
    }
  } else {
    cli::cli_alert_success("No test gaps detected!")
  }

  invisible(gaps)
}

# Script entry point
if (!interactive()) {
  detect_gaps()
}
