source(file.path("..", "..", "dev", "unit_test_readiness_audit.R"))

make_audit_repo <- function() {
  root <- tempfile("unit-test-audit-")
  dir.create(root, recursive = TRUE)
  root
}

write_audit_file <- function(root, rel_path, lines) {
  path <- file.path(root, rel_path)
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path, useBytes = TRUE)
  path
}

records_by_export <- function(comparison) {
  stats::setNames(
    comparison$export_inventory,
    vapply(comparison$export_inventory, `[[`, character(1), "export")
  )
}

test_that("namespace export parsing excludes operators and S3 methods from function-export gaps", {
  root <- make_audit_repo()
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  write_audit_file(root, "NAMESPACE", c(
    "S3method(print,thing)",
    "export(\"%>%\")",
    "export('%ni%')",
    "export(alpha)",
    "export(beta)"
  ))

  namespace <- audit_parse_namespace(root)

  expect_equal(namespace$operator_exports, c("%>%", "%ni%"))
  expect_equal(namespace$s3_methods, "print,thing")
  expect_equal(namespace$function_exports, c("alpha", "beta"))
  expect_false("%>%" %in% namespace$function_exports)
})

test_that("named test files and literal references classify exports separately", {
  root <- make_audit_repo()
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  write_audit_file(root, "tests/testthat/test-alpha.R", "test_that('alpha works', { alpha() })")
  write_audit_file(root, "tests/testthat/test-beta-name.R", "test_that('named file only', { expect_true(TRUE) })")
  write_audit_file(root, "tests/testthat/test-unrelated.R", "test_that('gamma referenced', { gamma_value <- gamma() })")

  comparison <- classify_exports_against_tests(
    c("alpha", "beta_name", "gamma"),
    sort(c(
      "tests/testthat/test-alpha.R",
      "tests/testthat/test-beta-name.R",
      "tests/testthat/test-unrelated.R"
    )),
    root
  )
  records <- records_by_export(comparison)

  expect_true(records$alpha$named_test_file)
  expect_true(records$alpha$literal_test_reference)
  expect_true(records$beta_name$named_test_file)
  expect_false(records$beta_name$literal_test_reference)
  expect_false(records$gamma$named_test_file)
  expect_true(records$gamma$literal_test_reference)
  expect_equal(comparison$export_gaps, "beta_name")
})

test_that("export exclusions require export reason owner and issue fields", {
  bad <- list(
    artifact_schema = "export_test_exclusions/v1",
    exclusions = list(list(export = "alpha", reason = "covered elsewhere"))
  )
  good <- list(
    artifact_schema = "export_test_exclusions/v1",
    exclusions = list(list(
      export = "alpha",
      reason = "covered by integration-only fixture",
      owner = "release",
      issue = "#190"
    ))
  )

  expect_false(validate_export_exclusions(bad, known_exports = "alpha")$valid)
  expect_true(validate_export_exclusions(good, known_exports = "alpha")$valid)
})

test_that("retired manifest is reported as non-authoritative", {
  root <- make_audit_repo()
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  write_audit_file(root, "dev/test_manifest.json", c(
    "{",
    '  "artifact_schema": "test_manifest_retired/v1",',
    '  "retired": true,',
    '  "authority": false,',
    '  "replacement": "dev/reports/unit_test_readiness_audit.json",',
    '  "legacy_manifest": { "files_total": 45 }',
    "}"
  ))

  status <- audit_manifest_status(root)

  expect_true(status$retired)
  expect_false(status$authoritative)
  expect_equal(status$replacement, "dev/reports/unit_test_readiness_audit.json")
  expect_equal(status$legacy_files_total, 45)
})

test_that("absent manifest is the normal retired state", {
  root <- make_audit_repo()
  on.exit(unlink(root, recursive = TRUE), add = TRUE)

  status <- audit_manifest_status(root)

  expect_false(status$exists)
  expect_true(status$retired)
  expect_false(status$authoritative)
  expect_equal(status$replacement, "dev/reports/unit_test_readiness_audit.json")
  expect_equal(status$legacy_files_total, 0)
})

test_that("generated-test static counters require a top-of-file generated header", {
  root <- make_audit_repo()
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  write_audit_file(root, "tests/testthat/test-alpha.R", c(
    "# Generated by dev/generate_tests.R; do not edit by hand.",
    "test_that('alpha passes request metadata', {",
    "  local_mocked_bindings(alpha = function() TRUE)",
    "})"
  ))
  write_audit_file(root, "tests/testthat/test-generator-fixture.R", c(
    "test_that('fixture text is not a generated test', {",
    "  marker <- '# Generated using metadata-based test generator'",
    "  call <- '`ct_chemical_by-dtxcid`()'",
    "  expect_true(nzchar(marker))",
    "  expect_true(nzchar(call))",
    "})"
  ))

  style <- audit_test_style(root)

  expect_equal(style$generated_header_test_files, 1)
  expect_equal(style$generated_backticked_endpoint_call_files, 0)
  expect_equal(style$non_generated_backticked_endpoint_call_files, 1)
  expect_equal(style$files_using_mocked_bindings, 1)
})

test_that("generated audit keeps schema unit_test_readiness_audit/v1", {
  root <- make_audit_repo()
  on.exit(unlink(root, recursive = TRUE), add = TRUE)
  write_audit_file(root, "NAMESPACE", "export(alpha)")
  write_audit_file(root, "tests/testthat/test-alpha.R", "test_that('alpha works', { alpha() })")
  write_audit_file(root, "dev/export_test_exclusions.json", c(
    "{",
    '  "artifact_schema": "export_test_exclusions/v1",',
    '  "required_fields": ["export", "reason", "owner", "issue"],',
    '  "exclusions": []',
    "}"
  ))

  output <- file.path(root, "dev/reports/unit_test_readiness_audit.json")
  report <- write_unit_test_readiness_audit(root, output)
  parsed <- jsonlite::fromJSON(output, simplifyVector = FALSE)

  expect_equal(report$artifact_schema, "unit_test_readiness_audit/v1")
  expect_equal(parsed$artifact_schema, "unit_test_readiness_audit/v1")
})
