# Tests for cc_search
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("cc_search passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_cc_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_cc_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(suppressWarnings(suppressMessages(ComptoxR::cc_search())), silent = TRUE)
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_cc_request")
  expect_equal(call[["endpoint"]], "search")
  expect_equal(call[["method"]], "GET")
  expect_equal(call[["max_pages"]], 100)
  expect_equal(call[["pagination_strategy"]], "offset_limit")
})
