# Tests for chemi_chet_curators_change_password
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("chemi_chet_curators_change_password passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_chemi_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_chemi_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(suppressWarnings(suppressMessages(ComptoxR::chemi_chet_curators_change_password(current_password = "DTXSID7020182", new_password = "DTXSID7020182"))), silent = TRUE)
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_chemi_request")
  expect_equal(call[["query"]], "DTXSID7020182")
  expect_equal(call[["endpoint"]], "curators/change-password")
  expect_true("options" %in% names(call))
  expect_true(is.null(call[["options"]]) || length(call[["options"]]) >= 0)
  expect_equal(call[["tidy"]], FALSE)
})
