# Tests for chemi_amos_product_declaration_keyset_pagination_bulk
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("chemi_amos_product_declaration_keyset_pagination_bulk passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(
    suppressWarnings(suppressMessages(ComptoxR::chemi_amos_product_declaration_keyset_pagination_bulk(limit = 1L))),
    silent = TRUE
  )
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_request")
  expect_null(call[["query"]])
  expect_equal(call[["endpoint"]], "amos/product_declaration_keyset_pagination/")
  expect_equal(call[["method"]], "POST")
  expect_equal(call[["batch_limit"]], 0)
  expect_equal(call[["auth"]], FALSE)
  expect_equal(call[["tidy"]], FALSE)
  expect_true("path_params" %in% names(call))
  expect_true(is.null(call[["path_params"]]) || length(call[["path_params"]]) >= 0)
  expect_true("body" %in% names(call))
  expect_true(is.null(call[["body"]]) || length(call[["body"]]) >= 0)
  expect_equal(call[["pagination_strategy"]], "cursor")
  expect_equal(call[["pagination_cursor_location"]], "body")
})
