# Tests for pubchem_search
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("pubchem_search passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_pubchem_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_pubchem_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(
    suppressWarnings(suppressMessages(ComptoxR::pubchem_search(query = "CCCC", type = "smiles", cache = FALSE))),
    silent = TRUE
  )
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_pubchem_request")
  expect_equal(call[["namespace"]], "smiles")
  expect_equal(call[["operation"]], "cids")
  expect_equal(call[["method"]], "POST")
  expect_true("body" %in% names(call))
  expect_true(is.null(call[["body"]]) || length(call[["body"]]) >= 0)
  expect_equal(call[["tidy"]], FALSE)
  expect_true("endpoint" %in% names(call) || "operation" %in% names(call))
})
