# Tests for chemi_predictor_modelset_report
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("chemi_predictor_modelset_report passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(
    suppressWarnings(suppressMessages(ComptoxR::chemi_predictor_modelset_report(report_id = 1L))),
    silent = TRUE
  )
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_request")
  expect_equal(call[["query"]], 1L)
  expect_equal(call[["endpoint"]], "predictor/modelset_report/")
  expect_equal(call[["method"]], "GET")
  expect_equal(call[["batch_limit"]], 1)
  expect_equal(call[["server"]], "chemi_burl")
  expect_equal(call[["auth"]], FALSE)
  expect_equal(call[["tidy"]], FALSE)
})
