# Tests for chemi_amos_get_substances_for_term
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("chemi_amos_get_substances_for_term passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(suppressWarnings(suppressMessages(ComptoxR::chemi_amos_get_substances_for_term(search_term = "DTXSID7020182"))), silent = TRUE)
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_request")
  expect_equal(call[["query"]], "DTXSID7020182")
  expect_equal(call[["endpoint"]], "amos/get_substances_for_search_term/")
  expect_equal(call[["method"]], "GET")
  expect_equal(call[["batch_limit"]], 1)
  expect_equal(call[["server"]], "chemi_burl")
  expect_equal(call[["auth"]], FALSE)
  expect_equal(call[["tidy"]], FALSE)
})
