# Tests for ct_exposure_mmdb_single_sample_by_medium
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("ct_exposure_mmdb_single_sample_by_medium passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(
    suppressWarnings(suppressMessages(ComptoxR::ct_exposure_mmdb_single_sample_by_medium(medium = "water"))),
    silent = TRUE
  )
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_request")
  expect_equal(call[["endpoint"]], "exposure/mmdb/single-sample/by-medium")
  expect_equal(call[["method"]], "GET")
  expect_equal(call[["batch_limit"]], 0)
  expect_equal(call[["medium"]], "water")
  expect_equal(call[["max_pages"]], 100)
  expect_equal(call[["pagination_strategy"]], "page_number")
})
