# Tests for ct_chemical_msready_search_by_mass
# Generated by dev/generate_tests.R; do not edit by hand.
# Generator: offline wrapper contract tests

test_that("ct_chemical_msready_search_by_mass passes request metadata to helper", {
  if (!exists("generated_contract_response", mode = "function")) {
    source(file.path("tests", "testthat", "helper-generated-contracts.R"))
  }
  generated_contract_ensure_package()

  calls <- list()
  mock_helper <- function(...) {
    captured <- list(...)
    captured$.helper <- "generic_request"
    calls[[length(calls) + 1L]] <<- captured
    generated_contract_response(...)
  }

  testthat::local_mocked_bindings(
    generic_request = mock_helper,
    .package = "ComptoxR"
  )

  result <- try(
    suppressWarnings(suppressMessages(ComptoxR::ct_chemical_msready_search_by_mass(start = 1L))),
    silent = TRUE
  )
  expect_gt(length(calls), 0L)
  call <- calls[[1L]]
  expect_true(is.list(call))
  expect_equal(call$.helper, "generic_request")
  expect_equal(call[["query"]], 1L)
  expect_equal(call[["endpoint"]], "chemical/msready/search/by-mass/")
  expect_equal(call[["method"]], "GET")
  expect_equal(call[["batch_limit"]], 1)
  expect_true("path_params" %in% names(call))
  expect_true(is.null(call[["path_params"]]) || length(call[["path_params"]]) >= 0)
})
