installed_runtime <- function(root = '.') {
  root <- normalizePath(root, winslash = '/', mustWork = TRUE)
  lib <- file.path(root, 'dev/migration-evidence/.runtime-library')
  dir.create(lib, showWarnings = FALSE)
  dependencies <- c('testthat', 'httr2')
  fields <- read.dcf(file.path(root, 'DESCRIPTION'))
  for (field in intersect(c('Imports', 'Depends'), colnames(fields))) {
    dependencies <- c(dependencies, trimws(sub(' *\\(.*', '', strsplit(fields[[1, field]], ',')[[1]])))
  }
  dependencies <- setdiff(dependencies, c('R', 'wrapmaint'))
  all <- unique(c(
    dependencies,
    unlist(tools::package_dependencies(
      dependencies,
      db = installed.packages(),
      which = c('Depends', 'Imports', 'LinkingTo'),
      recursive = TRUE
    ))
  ))
  for (package in setdiff(all, c('R', 'wrapmaint'))) {
    path <- find.package(package)
    if (!startsWith(normalizePath(path, winslash = '/'), normalizePath(.Library, winslash = '/'))) {
      if (!dir.exists(file.path(lib, package))) stopifnot(file.copy(path, lib, recursive = TRUE))
    }
  }
  fixture <- system.file('catalogue', package = 'wrapmaint', mustWork = TRUE)
  catalogue <- tempfile('runtime-catalogue-')
  dir.create(catalogue)
  file.copy(list.files(fixture, full.names = TRUE), catalogue, recursive = TRUE)
  wrapmaint::generate_client(
    catalogue,
    list(
      files = file.path(catalogue, 'schema.json'),
      helper = 'catalogue_request',
      hooks = list(get_item = list(pre_request = 'normalize_input', post_response = 'extract_output'))
    ),
    'apply'
  )
  for (client in c(root, catalogue)) {
    status <- system2(
      file.path(R.home('bin'), if (.Platform$OS.type == 'windows') 'R.exe' else 'R'),
      c('CMD', 'INSTALL', paste0('--library=', shQuote(lib)), shQuote(client))
    )
    stopifnot(status == 0L)
  }
  script <- file.path(root, 'dev/migration-evidence/installed-runtime.R')
  status <- system2(
    file.path(R.home('bin'), if (.Platform$OS.type == 'windows') 'Rscript.exe' else 'Rscript'),
    c('--vanilla', shQuote(script), '--runtime', shQuote(lib), shQuote(root))
  )
  stopifnot(status == 0L)
  writeLines(
    c(
      paste('Isolated library:', lib),
      paste('Installed dependency packages:', length(all)),
      'Installed ComptoxR and localcatalogue run with wrapmaint absent from every runtime library.'
    ),
    file.path(root, 'dev/migration-evidence/toolkit-runtime.txt')
  )
}
if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) && args[[1]] == '--runtime') {
    .libPaths(c(args[[2]], .Library))
    stopifnot(!requireNamespace('wrapmaint', quietly = TRUE))
    library(ComptoxR)
    library(localcatalogue)
    localcatalogue::clear_calls()
    stopifnot(
      identical(localcatalogue::get_item(' x '), 'ok'),
      identical(localcatalogue::captured()[[1]]$path_params$item_id, 'x')
    )
    # Run committed offline helper-call contracts against the installed client.
    dir <- file.path(args[[3]], 'tests/testthat')
    helper <- new.env(parent = globalenv())
    sys.source(file.path(dir, 'helper-generated-contracts.R'), envir = helper)
    tests <- list.files(dir, '^test-.*\\.R$', full.names = TRUE)
    generated <- tests[vapply(
      tests,
      function(file) {
        any(grepl(
          '# Generated by dev/generate_tests.R; do not edit by hand.',
          readLines(file, n = 5L),
          fixed = TRUE
        ))
      },
      logical(1)
    )]
    for (file in generated) {
      testthat::test_file(file, env = helper, reporter = 'silent', load_helpers = FALSE, stop_on_failure = TRUE)
    }
    stopifnot(!'wrapmaint' %in% loadedNamespaces())
    cat(length(generated), 'installed ComptoxR generated contract files passed with no toolkit available.\n')
  } else {
    installed_runtime()
  }
}
