# Generated by specmill; client-owned HTTP runtime.
.ct_request <- function(method, path, path_params, query, body, headers = base::list(), query_serialization = base::list(), body_media = 'application/json', auth = NULL, batch = base::list(), parameter_serialization = base::list(), cookies = base::list(), body_encoding = base::list(), form_schema = NULL, server = base::list(url = "https://example.invalid"), request_controls = base::list(), response_policy = base::getOption(base::paste0(base::tolower(base::sub('_DRY_RUN$', '', "COMPTOXR_NATIVE_DRY_RUN")), '.response_policy'))) {
  if (base::is.character(response_policy) && base::length(response_policy) == 1L && !base::is.na(response_policy)) {
    policy_name <- response_policy
    response_policy <- base::get0(policy_name, envir = base::parent.env(base::environment()), mode = 'function', inherits = FALSE)
    if (base::is.null(response_policy)) base::stop('Missing client response policy: ', policy_name, call. = FALSE)
  }
  if (!base::is.null(response_policy) && !base::is.function(response_policy)) base::stop('response_policy must be NULL, a function, or a client function name', call. = FALSE)
  # Runtime options use the same package prefix as the dry-run environment flag.
  option_prefix <- base::tolower(base::sub('_DRY_RUN$', '', "COMPTOXR_NATIVE_DRY_RUN"))
  controls <- base::getOption(base::paste0(option_prefix, '.request'), base::list())
  verbose <- base::getOption(base::paste0(option_prefix, '.run_verbose'), FALSE)
  dry <- base::getOption(base::paste0(option_prefix, '.dry_run'), base::tolower(base::Sys.getenv("COMPTOXR_NATIVE_DRY_RUN")) %in% base::c('true', '1', 'yes'))
  for (flag in base::list(verbose = verbose, dry_run = dry)) {
    if (!base::is.logical(flag) || base::length(flag) != 1L || base::is.na(flag)) base::stop('run_verbose and dry_run options must be TRUE or FALSE', call. = FALSE)
  }
  if (!base::is.list(controls) || (base::length(controls) && (base::is.null(base::names(controls)) || base::anyNA(base::names(controls)) || base::anyDuplicated(base::names(controls)))) || base::length(base::setdiff(base::names(controls), base::c('base_url', 'timeout', 'max_retries', 'retry_writes', 'retry_policy')))) base::stop('Request controls must be a named list of base_url, timeout, max_retries, retry_writes, retry_policy', call. = FALSE)
  for (name in base::c('timeout', 'max_retries', 'retry_writes', 'retry_policy')) {
    if (base::is.null(controls[[name]])) controls[[name]] <- request_controls[[name]]
  }
  timeout <- if (base::is.null(controls$timeout)) 30 else controls$timeout
  retries <- if (base::is.null(controls$max_retries)) 0 else controls$max_retries
  writes <- if (base::is.null(controls$retry_writes)) FALSE else controls$retry_writes
  if (!base::is.numeric(timeout) || base::length(timeout) != 1L || !base::is.finite(timeout) || timeout <= 0) base::stop('timeout must be a finite positive number of seconds', call. = FALSE)
  if (!base::is.numeric(retries) || base::length(retries) != 1L || !base::is.finite(retries) || retries < 0 || retries != base::trunc(retries) || retries >= base::.Machine$integer.max) base::stop('max_retries must be a nonnegative integer below .Machine$integer.max', call. = FALSE)
  if (!base::is.logical(writes) || base::length(writes) != 1L || base::is.na(writes)) base::stop('retry_writes must be TRUE or FALSE', call. = FALSE)
  retry_policy <- controls$retry_policy
  if (base::is.character(retry_policy) && base::length(retry_policy) == 1L && !base::is.na(retry_policy) && base::identical(base::make.names(retry_policy), retry_policy)) {
    retry_policy <- base::get0(retry_policy, envir = base::parent.env(base::environment()), mode = 'function', inherits = FALSE)
    if (base::is.null(retry_policy)) base::stop('Missing client retry policy', call. = FALSE)
  }
  if (!base::is.null(retry_policy) && !base::is.function(retry_policy)) base::stop('retry_policy must be NULL, a function, or a client function name', call. = FALSE)
  is_transient <- if (base::is.null(retry_policy)) {
    function(response) httr2::resp_status(response) %in% base::c(408L, 429L, 500L, 502L, 503L, 504L)
  } else function(response) {
    transient <- base::tryCatch(retry_policy(response), error = function(e) base::stop('Client retry policy failed', call. = FALSE))
    if (!base::is.logical(transient) || base::length(transient) != 1L || base::is.na(transient)) base::stop('Client retry policy must return TRUE or FALSE', call. = FALSE)
    transient
  }
  base_url_override <- NULL # Initialization override
  base_url <- controls$base_url
  if (base::is.null(base_url)) base_url <- base_url_override
  if (base::is.null(base_url)) {
    if (!base::is.null(server$diagnostic)) base::stop('Server selection: ', server$diagnostic, call. = FALSE)
    base_url <- server$url
  }
  valid_url <- base::is.character(base_url) && base::length(base_url) == 1L && !base::is.na(base_url) &&
    base::grepl('^https?://([A-Za-z0-9.-]+|\\[[0-9A-Fa-f:]+\\])(:[0-9]+)?(/[^?#]*)?$', base_url) &&
    !base::grepl('[[:space:]{}\\\\]', base_url) && !base::grepl('%(?![0-9A-Fa-f]{2})', base_url, perl = TRUE)
  if (valid_url) valid_url <- !base::is.null(base::tryCatch(curl::curl_parse_url(base_url), error = function(e) NULL)) &&
    !base::grepl(':0$', base::sub('^https?://([^/]+).*$', '\\1', base_url))
  if (!valid_url) base::stop('base_url must be absolute HTTP(S) without credentials, query, fragment, or unresolved variables', call. = FALSE)
  encode_parameter <- function(value, p) {
    if (base::is.null(value)) {
      if (base::isTRUE(p$required)) base::stop('Required parameter: ', p$name)
      base::return(base::character())
    }
    type <- p$schema$type
    style <- p$style
    explode <- base::isTRUE(p$explode)
    scalar <- function(x, schema) {
      valid <- !base::is.object(x) && base::is.null(base::dim(x)) && base::is.null(base::names(x)) && base::length(x) == 1L && !base::anyNA(x) &&
        (base::is.character(x) || base::is.logical(x) || (base::is.numeric(x) && base::is.finite(x)))
      if (valid && !base::is.null(schema$type)) valid <- base::switch(schema$type,
        string = base::is.character(x), boolean = base::is.logical(x),
        number = base::is.numeric(x), integer = base::is.numeric(x) && x == base::trunc(x), FALSE)
      if (!valid) base::stop('Parameter must contain finite, non-null scalars of its declared type: ', p$name)
      if (base::is.logical(x)) if (x) 'true' else 'false' else base::as.character(x)
    }
    if (base::is.object(value) || !base::is.null(base::dim(value))) base::stop('Parameter must be a plain vector or list: ', p$name)
    keys <- base::names(value)
    if (base::identical(type, 'object')) {
      if (!base::is.list(value) || (base::length(value) && base::is.null(keys)) || base::anyNA(keys) || base::anyDuplicated(keys) || base::any(!base::nzchar(keys))) base::stop('Object parameter must be a uniquely named list: ', p$name)
      if (!base::all(base::unlist(p$schema$required) %in% keys)) base::stop('Missing required parameter fields: ', p$name)
      if (base::isFALSE(p$schema$additionalProperties) && base::length(base::setdiff(keys, base::names(p$schema$properties)))) base::stop('Unknown parameter fields: ', p$name)
      values <- base::vapply(base::seq_along(value), function(i) {
        child <- p$schema$properties[[keys[[i]]]]
        if (base::is.null(child) && base::is.list(p$schema$additionalProperties)) child <- p$schema$additionalProperties
        scalar(value[[i]], child)
      }, base::character(1))
    } else if (base::identical(type, 'array')) {
      if (!base::is.null(keys) || !(base::is.atomic(value) || base::is.list(value))) base::stop('Array parameter must be an unnamed vector or list: ', p$name)
      if ((!base::is.null(p$schema$minItems) && base::length(value) < p$schema$minItems) || (!base::is.null(p$schema$maxItems) && base::length(value) > p$schema$maxItems)) base::stop('Invalid parameter array length: ', p$name)
      values <- base::vapply(value, scalar, base::character(1), schema = p$schema$items)
    } else values <- scalar(value, p$schema)
    # URI templates do not define a distinct representation for an empty list/map.
    if (type %in% base::c('array', 'object') && !base::length(values)) base::stop('Empty parameter containers cannot be encoded unambiguously: ', p$name)
    if (p$location == 'header') {
      if (base::any(base::grepl('[\r\n]', base::c(keys, values)))) base::stop('Newlines are forbidden in header parameters')
      separator <- if (base::is.null(p$collection_format)) ',' else base::switch(p$collection_format, ssv = ' ', tsv = '\t', pipes = '|', ',')
      if (type %in% base::c('array', 'object') &&
          (base::any(base::grepl(separator, base::c(keys, values), fixed = TRUE)) ||
           (type == 'object' && explode && base::any(base::grepl('=', base::c(keys, values), fixed = TRUE))))) base::stop('Header parameter values contain serialization delimiters')
      encode <- base::identity
    } else {
      separator <- if (base::identical(p$collection_format, 'tsv')) '\t' else if (style == 'spaceDelimited' || base::identical(p$collection_format, 'ssv')) ' ' else NULL
      if (!explode && !base::is.null(separator) && base::any(base::grepl(separator, base::c(keys, values), fixed = TRUE))) base::stop('Parameter values contain an ambiguous whitespace delimiter')
      encode <- function(x) utils::URLencode(base::enc2utf8(x), reserved = TRUE, repeated = TRUE)
    }
    values <- base::vapply(values, encode, base::character(1), USE.NAMES = FALSE)
    keys <- base::vapply(keys, encode, base::character(1), USE.NAMES = FALSE)
    name <- encode(p$name)
    delimiter <- if (!base::is.null(p$collection_format)) base::switch(p$collection_format, csv = ',', ssv = '%20', tsv = '%09', pipes = '|', multi = ',') else base::switch(style, spaceDelimited = '%20', pipeDelimited = '|', ',')
    if (p$location == 'header') delimiter <- if (!base::is.null(p$collection_format)) base::switch(p$collection_format, ssv = ' ', tsv = '\t', pipes = '|', ',') else ','
    flat <- if (base::identical(type, 'object')) base::as.vector(base::rbind(keys, values)) else values
    if (p$location %in% base::c('query', 'cookie')) {
      if (style == 'brackets') base::return(base::paste0(name, '%5B%5D=', values))
      if (style == 'deepObject') base::return(base::paste0(name, '[', keys, ']=', values))
      if (explode && base::identical(type, 'object')) base::return(base::paste0(keys, '=', values))
      if (explode && base::identical(type, 'array')) base::return(base::paste0(name, '=', values))
      base::return(base::paste0(name, '=', base::paste(flat, collapse = delimiter)))
    }
    if (style == 'matrix') {
      if (explode && base::identical(type, 'object')) base::return(base::paste0(';', base::paste0(keys, '=', values, collapse = ';')))
      if (explode && base::identical(type, 'array')) base::return(base::paste0(';', base::paste0(name, '=', values, collapse = ';')))
      base::return(base::paste0(';', name, if (base::length(flat) == 1L && flat == '') '' else base::paste0('=', base::paste(flat, collapse = ','))))
    }
    if (base::identical(type, 'object') && explode) flat <- base::paste0(keys, '=', values)
    if (style == 'label' && explode) {
      # Escape literal dots before adding label separators.
      flat <- base::gsub('.', '%2E', flat, fixed = TRUE)
      delimiter <- '.'
    }
    base::paste0(if (style == 'label') '.' else '', base::paste(flat, collapse = delimiter))
  }
  encoded_query <- base::list()
  encoded_cookies <- base::list()
  for (p in parameter_serialization) {
    values <- base::switch(p$location, path = path_params, query = query, header = headers, cookie = cookies)
    encoded <- encode_parameter(values[[p$name]], p)
    if (p$location == 'path') {
      path <- base::gsub(base::paste0('{', p$name, '}'), encoded, path, fixed = TRUE)
      path_params[p$name] <- NULL
    } else if (p$location == 'query') {
      encoded_query[[base::length(encoded_query) + 1L]] <- encoded
      query[p$name] <- NULL
    } else if (p$location == 'header') {
      headers[p$name] <- if (base::length(encoded)) base::list(encoded) else base::list(NULL)
    } else encoded_cookies[[base::length(encoded_cookies) + 1L]] <- encoded
  }
  for (limit in batch) {
    if (!base::is.numeric(limit) || base::length(limit) != 1L || base::is.na(limit) || !base::is.finite(limit) || limit < 1 || limit != base::floor(limit)) base::stop('Batch limits must be positive integers')
  }
  if (!base::is.null(batch$max_items) && !base::is.null(body)) {
    # Split oversized input with the selected client-owned batching companion, or:
    # lapply(split(items, ceiling(seq_along(items) / size)), fn, ...)
    if (!base::is.list(body) || !base::is.null(base::names(body))) base::stop('Batch body must be an unnamed list of items')
    if (base::length(body) > batch$max_items) base::stop('Batch exceeds max_items (', batch$max_items, '); split the input into smaller requests')
  }
  for (name in base::names(path_params)) {
    path <- base::gsub(base::paste0('{', name, '}'), utils::URLencode(base::as.character(path_params[[name]]), reserved = TRUE), path, fixed = TRUE)
  }
  request <- httr2::request(base_url)
  request <- httr2::req_method(request, method)
  query <- base::Filter(base::Negate(base::is.null), query)
  for (name in base::names(query)) {
    serialization <- query_serialization[[name]]
    if (base::is.null(serialization)) serialization <- 'error'
    if (name %in% base::names(query_serialization)) {
      if (!serialization %in% base::c('comma', 'explode')) base::stop('Unsupported query array serialization')
      if (!base::is.character(query[[name]]) || base::anyNA(query[[name]])) base::stop('Query array must be a character vector without missing values')
      encoded_query[[base::length(encoded_query) + 1L]] <- encode_parameter(query[[name]], base::list(name = name, location = 'query', schema = base::list(type = 'array', items = base::list(type = 'string')), style = 'form', explode = serialization == 'explode'))
    } else request <- base::do.call(httr2::req_url_query, base::c(base::list(request, .multi = serialization), query[name]))
  }
  headers <- base::Filter(base::Negate(base::is.null), headers)
  if (base::length(headers)) request <- base::do.call(httr2::req_headers, base::c(base::list(request), headers))
  suffix <- if (base::grepl('?', request$url, fixed = TRUE)) base::sub('^[^?]*', '', request$url) else ''
  request <- httr2::req_url(request, base::paste0(base::sub('/+$', '', base_url), '/', base::sub('^/+', '', path), suffix))
  encoded_query <- base::unlist(encoded_query, use.names = FALSE)
  encoded_cookies <- base::unlist(encoded_cookies, use.names = FALSE)
  if (base::length(encoded_cookies)) {
    prior <- request$headers[['Cookie']]
    request <- httr2::req_headers(request, Cookie = base::paste(base::c(prior, encoded_cookies), collapse = '; '))
  }
  if (!base::is.null(body) && body_media %in% base::c('application/x-www-form-urlencoded', 'multipart/form-data')) {
    if (!base::is.list(body) || (base::length(body) && base::is.null(base::names(body)))) base::stop('Form body must be a named list')
    parts <- base::list()
    pairs <- base::character()
    for (name in base::names(body)) {
      field <- form_schema$properties[[name]]
      if (base::is.null(field) && base::is.list(form_schema$additionalProperties)) field <- form_schema$additionalProperties
      if (base::is.null(field$type)) base::stop('Form field needs a declared schema: ', name)
      value <- body[[name]]
      if (base::is.null(value)) base::stop('Null form fields cannot be encoded')
      enc <- body_encoding[[name]]
      if (base::is.null(enc)) enc <- base::list()
      if (body_media == 'application/x-www-form-urlencoded') {
        style <- if (base::is.null(enc$style)) 'form' else enc$style
        explode <- if (base::is.null(enc$explode)) style == 'form' else enc$explode
        if (!base::is.null(enc$collection_format)) explode <- enc$collection_format == 'multi'
        pairs <- base::c(pairs, encode_parameter(value, base::list(name = name, location = 'query', schema = field, style = style, explode = explode, collection_format = enc$collection_format)))
      } else {
        array <- base::identical(field$type, 'array')
        values <- if (array) value else base::list(value)
        if (!base::length(values)) base::stop('Empty multipart arrays cannot be encoded unambiguously')
        item <- if (array) field$items else field
        content_type <- enc$contentType
        if (base::is.null(content_type)) content_type <- if (base::identical(item$format, 'binary')) 'application/octet-stream' else if (base::identical(item$type, 'object')) 'application/json' else 'text/plain'
        scalar <- function(x) {
          if (base::is.logical(x)) { if (x) 'true' else 'false' } else base::as.character(x)
        }
        if (array && !base::is.null(enc$collection_format) && enc$collection_format != 'multi') {
          delimiter <- base::switch(enc$collection_format, csv = ',', ssv = ' ', tsv = '\t', pipes = '|')
          tokens <- base::vapply(values, scalar, base::character(1))
          if (base::any(base::grepl(delimiter, tokens, fixed = TRUE))) base::stop('Multipart values contain a serialization delimiter')
          values <- base::list(base::paste(tokens, collapse = delimiter))
        }
        for (part in values) {
          if (base::identical(item$format, 'binary')) {
            if (base::inherits(part, 'form_file')) {
              part$type <- content_type
            } else if (base::is.raw(part)) part <- curl::form_data(part, type = content_type)
            else base::stop('Binary form fields require raw or curl::form_file()')
          } else if (content_type == 'application/json') {
            part <- curl::form_data(base::as.character(jsonlite::toJSON(part, auto_unbox = TRUE, null = 'null', digits = 22)), type = content_type)
          } else part <- curl::form_data(scalar(part), type = content_type)
          parts <- base::c(parts, stats::setNames(base::list(part), name))
        }
      }
    }
    if (body_media == 'application/x-www-form-urlencoded') request <- httr2::req_body_raw(request, base::paste(pairs, collapse = '&'), type = body_media)
    else request <- base::do.call(httr2::req_body_multipart, base::c(base::list(request), parts))
  } else if (!base::is.null(body)) {
    if (base::identical(body_media, 'text/plain')) {
      if (!base::is.character(body) || base::is.object(body) || !base::is.null(base::dim(body)) || !base::is.null(base::names(body)) || base::length(body) != 1L || base::anyNA(body)) base::stop('Plain-text body must be one nonmissing character string', call. = FALSE)
      body <- base::charToRaw(base::enc2utf8(body))
    }
    if (!base::is.null(batch$max_bytes)) {
      bytes <- if (base::identical(body_media, 'application/json')) {
        base::charToRaw(base::enc2utf8(base::as.character(jsonlite::toJSON(body, auto_unbox = TRUE, null = 'null', digits = 22))))
      } else body
      if (!base::is.raw(bytes)) base::stop('Binary body must be a raw vector')
      if (base::length(bytes) > batch$max_bytes) base::stop('Batch exceeds max_bytes (', batch$max_bytes, ')')
      request <- httr2::req_body_raw(request, bytes, type = body_media)
    } else
    if (base::identical(body_media, 'text/plain')) {
      request <- httr2::req_body_raw(request, body, type = body_media)
    } else if (base::identical(body_media, 'application/octet-stream')) {
      if (!base::is.raw(body)) base::stop('Binary body must be a raw vector')
      request <- httr2::req_body_raw(request, body, type = body_media)
    } else if (base::identical(body_media, 'application/json')) {
      request <- httr2::req_body_json(request, body, auto_unbox = TRUE, null = 'null')
    } else base::stop('Unsupported request body media type')
  }
  if (!base::is.null(auth)) {
    authenticate <- base::get0('api_auth', envir = base::environment(), mode = 'function', inherits = TRUE)
    if (base::is.null(authenticate)) base::stop('Authentication scaffolding is missing')
    request <- authenticate(request, auth)
  }
  if (base::length(encoded_cookies)) request <- httr2::req_headers(request, .redact = 'Cookie')
  # Append encoded tokens last: query authentication must not decode/re-encode them.
  if (base::length(encoded_query)) request <- httr2::req_url(request, base::paste0(request$url, if (base::grepl('?', request$url, fixed = TRUE)) '&' else '?', base::paste(encoded_query, collapse = '&')))
  request <- httr2::req_timeout(request, timeout)
  if (retries > 0 && (base::toupper(method) %in% base::c('GET', 'HEAD', 'OPTIONS', 'PUT', 'DELETE') || writes)) {
    request <- httr2::req_retry(request, max_tries = retries + 1,
      is_transient = is_transient)
  }
  if (verbose) base::message(base::toupper(method), if (dry) ' request (dry run)' else ' request')
  if (dry) base::return(request)
  request <- httr2::req_error(request, is_error = function(response) FALSE)
  response <- base::tryCatch(httr2::req_perform(request), error = function(e) {
    base::stop('HTTP request failed before a response was received (connection, TLS, or timeout failure)', call. = FALSE)
  })
  .ct_request_decode(response, method, response_policy)
}

.ct_request_decode <- function(response, method = "GET", response_policy = NULL) {
  status <- httr2::resp_status(response)
  media <- httr2::resp_header(response, 'content-type')
  if (base::is.null(media)) media <- ''
  media <- base::tolower(base::trimws(base::sub(';.*$', '', media)))
  diagnostic <- base::paste0('HTTP ', status, if (base::nzchar(media)) base::paste0(' ', media) else '')
  # Captures the final response. Policy return values, including NULL, are results.
  decode <- function(format = 'native', check_status = TRUE, col_classes = NA) {
    format <- base::match.arg(format, base::c('native', 'delimited'))
    if (!base::is.logical(check_status) || base::length(check_status) != 1L || base::is.na(check_status)) base::stop('check_status must be TRUE or FALSE', call. = FALSE)
    if (check_status && status >= 400L) base::stop(diagnostic, ' response', call. = FALSE)
    delimited <- format == 'delimited' && media %in% base::c('text/csv', 'application/csv', 'text/tab-separated-values', 'text/tsv')
    if (!httr2::resp_has_body(response) || !base::length(httr2::resp_body_raw(response))) {
      base::return(if (delimited) base::data.frame() else NULL)
    }
    if (delimited) {
      text <- httr2::resp_body_string(response)
      separator <- if (media %in% base::c('text/tab-separated-values', 'text/tsv')) '\t' else ','
      connection <- base::textConnection(text)
      base::on.exit(base::close(connection), add = TRUE)
      # read.table otherwise infers row names when every row has an extra field.
      counts <- base::withCallingHandlers(utils::count.fields(connection, sep = separator, quote = '"', comment.char = ''), warning = function(w) base::stop(base::conditionMessage(w), call. = FALSE))
      counts <- counts[!base::is.na(counts)]
      if (!base::length(counts)) base::return(base::data.frame())
      if (base::any(counts != counts[[1L]])) base::stop('Malformed delimited response: inconsistent field counts', call. = FALSE)
      base::return(base::withCallingHandlers(utils::read.table(text = text, header = TRUE, sep = separator, quote = '"', comment.char = '', check.names = FALSE, stringsAsFactors = FALSE, fill = FALSE, colClasses = col_classes), warning = function(w) base::stop(base::conditionMessage(w), call. = FALSE)))
    }
    if (base::grepl('(/json|\\+json)$', media)) {
      decoded <- base::tryCatch(jsonlite::fromJSON(httr2::resp_body_string(response), simplifyVector = FALSE), error = base::identity)
      if (base::inherits(decoded, 'error')) base::stop('Cannot decode ', diagnostic, ' response as JSON', call. = FALSE)
      base::return(decoded)
    }
    if (base::startsWith(media, 'text/') || media == 'image/svg+xml') base::return(httr2::resp_body_string(response))
    httr2::resp_body_raw(response)
  }
  if (base::is.null(response_policy)) base::return(decode())
  response_policy(response, base::list(method = base::toupper(method), status = status, media = media), decode)
}

# Select once in service defaults; actual response media chooses the delimiter.
.ct_request_delimited <- function(response, context, decode) decode(format = 'delimited')

# Explicit collection formatting, suitable for an existing post_response hook.
.ct_request_records <- function(result, collection = base::character(), query = NULL, null_to_na = FALSE, keyed = FALSE) {
  if (!base::is.character(collection) || base::anyNA(collection)) base::stop('collection must be a character path')
  for (field in collection) {
    if (!base::is.list(result) || !field %in% base::names(result)) base::stop('Missing collection field: ', field)
    result <- result[[field]]
  }
  records <- if (base::is.null(result) || !base::length(result)) base::list() else if (base::is.data.frame(result)) {
    base::lapply(base::seq_len(base::nrow(result)), function(i) base::as.list(result[i, , drop = FALSE]))
  } else if (base::is.list(result)) {
    if (!keyed && !base::is.null(base::names(result))) base::list(result) else result
  } else base::as.list(result)
  if (!base::is.null(query) && base::length(query) != 1L && base::length(query) != base::length(records)) base::stop('query must have length one or match records')
  formatted <- base::lapply(base::seq_along(records), function(i) {
    record <- records[[i]]
    if (null_to_na && base::is.list(record)) record[base::vapply(record, base::is.null, base::logical(1))] <- NA
    if (!base::is.null(query) && !base::is.null(record)) base::attr(record, 'query') <- query[if (base::length(query) == 1L) 1L else i]
    record
  })
  stats::setNames(formatted, base::names(records))
}

# Selected compatibility table: collapse nested fields, then optionally recover types.
# Supply tibble::as_tibble as as_table only in a client that declares tibble in Imports.
.ct_request_table <- function(records, type_convert = TRUE, names_to = NULL, as_table = base::identity) {
  if (!base::is.list(records) || !base::is.function(as_table)) base::stop('Supply records as a list and as_table as a function')
  rows <- base::lapply(base::seq_along(records), function(i) {
    record <- records[[i]]
    if (base::is.null(record) || !base::length(record)) base::return(NULL)
    query <- base::attr(record, 'query', exact = TRUE)
    if (!base::is.list(record)) record <- base::list(value = record)
    if (base::is.null(base::names(record)) || base::anyNA(base::names(record)) || base::anyDuplicated(base::names(record))) base::stop('Table records must have unique field names')
    row <- base::lapply(record, function(value) {
      if (base::is.null(value) || !base::length(value)) NA_character_
      else base::paste(base::as.character(base::unlist(value)), collapse = '; ')
    })
    if (!base::is.null(query)) {
      if ('query' %in% base::names(row)) base::stop('Query attribution would replace a record field')
      row$query <- base::as.character(query)
    }
    if (!base::is.null(names_to)) {
      if (!base::is.character(names_to) || base::length(names_to) != 1L || base::is.na(names_to) || !base::nzchar(names_to) || names_to %in% base::names(row)) base::stop('names_to must name a new column')
      row[[names_to]] <- if (base::is.null(base::names(records))) base::as.character(i) else base::names(records)[[i]]
    }
    row
  })
  rows <- base::Filter(base::Negate(base::is.null), rows)
  if (!base::length(rows)) base::return(as_table(base::data.frame()))
  fields <- base::unique(base::unlist(base::lapply(rows, base::names), use.names = FALSE))
  columns <- base::lapply(fields, function(field) {
    values <- base::vapply(rows, function(row) if (base::is.null(row[[field]])) NA_character_ else row[[field]], base::character(1))
    if (type_convert) utils::type.convert(values, as.is = TRUE) else values
  })
  result <- base::structure(stats::setNames(columns, fields), class = 'data.frame', row.names = base::seq_along(rows))
  as_table(result)
}

#' Client-owned batched companion
#' @param fn Client-owned single-request function to call.
#' @param items Batch inputs, or an explicit response collection extractor for pagination.
#' @param size Positive integer maximum batch length.
#' @param ... Fixed arguments passed unchanged to the single-request function.
#' @param policy Named list of explicit shared client choices; individual pagination arguments override it.
#' @noRd
.ct_request_batched <- function(fn, items, size, ..., policy = base::getOption(base::paste0(base::tolower(base::sub("_DRY_RUN$",
    "", "COMPTOXR_NATIVE_DRY_RUN")), "..ct_request.batching"), base::list())) {
    if (!base::is.numeric(size) || base::length(size) != 1L || base::is.na(size) ||
        !base::is.finite(size) || size < 1 || size != base::floor(size)) {
        base::stop("size must be a positive integer")
    }
    if (!base::is.function(fn)) {
        base::stop("fn must be a function")
    }
    allowed <- base::c("normalize", "build", "merge", "on_error", "error_result",
        "first_batch_only")
    if (!base::is.list(policy) || (base::length(policy) && (base::is.null(base::names(policy)) ||
        base::anyNA(base::names(policy)) || base::anyDuplicated(base::names(policy)))) ||
        base::length(base::setdiff(base::names(policy), allowed))) {
        base::stop("policy must be a named list of normalize, build, merge, on_error, error_result, first_batch_only")
    }
    for (name in base::c("normalize", "build", "merge")) {
        if (!base::is.null(policy[[name]]) && !base::is.function(policy[[name]])) {
            base::stop(name, " must be a function")
        }
    }
    on_error <- if (base::is.null(policy$on_error))
        "stop"
    else policy$on_error
    if (base::length(on_error) != 1L || base::is.na(on_error) || !on_error %in% base::c("stop",
        "drop", "keep")) {
        base::stop("on_error must be stop, drop, or keep")
    }
    if (!base::is.null(policy$first_batch_only) && !base::identical(policy$first_batch_only,
        TRUE) && !base::identical(policy$first_batch_only, FALSE)) {
        base::stop("first_batch_only must be TRUE or FALSE")
    }
    if (!base::is.null(policy$normalize)) {
        items <- policy$normalize(items)
    }
    chunks <- base::split(items, base::ceiling(base::seq_along(items)/size))
    if (base::isTRUE(policy$first_batch_only) && base::length(chunks)) {
        chunks <- chunks[1L]
    }
    results <- base::list()
    for (index in base::seq_along(chunks)) {
        chunk <- chunks[[index]]
        if (!base::is.null(policy$build)) {
            chunk <- policy$build(chunk, index)
        }
        result <- if (on_error == "stop") {
            base::list(value = fn(chunk, ...), failed = FALSE)
        }
        else {
            base::tryCatch(base::list(value = fn(chunk, ...), failed = FALSE), error = function(error) {
                base::warning("Batch ", index, " failed: ", base::conditionMessage(error),
                  call. = FALSE)
                base::list(value = policy$error_result, failed = TRUE)
            })
        }
        if (!result$failed || on_error == "keep") {
            results[base::names(chunks)[index]] <- base::list(result$value)
        }
    }
    if (base::is.null(policy$merge))
        results
    else policy$merge(results)
}

#' Client-owned paginated companion
#' @param fn Client-owned single-request function to call.
#' @param ... Fixed arguments passed unchanged to the single-request function.
#' @param mode Explicit page, offset, or cursor strategy.
#' @param parameter Exact public argument name or nested character-vector argument path.
#' @param size_parameter Exact argument name or nested path for the page size.
#' @param page_size Positive integer requested page size.
#' @param start Initial page/offset integer, or initial opaque cursor string or NULL.
#' @param items Batch inputs, or an explicit response collection extractor for pagination.
#' @param max_pages Positive integer call bound, default 100.
#' @param max_items Optional positive integer retained-item bound; NULL means no item cap.
#' @param next_cursor Function extracting an opaque next cursor string or NULL.
#' @param completed Optional function of response and state selecting metadata completion.
#' @param advance Optional function of response, position and page_size returning the next position.
#' @param stop_on_short Whether a short page signals completion, default FALSE.
#' @param error_policy Request error policy: stop by default, or explicit partial/empty recovery with warnings.
#' @param warn_limits Whether truncation warns, default TRUE in emitted companions.
#' @param format Optional final-result formatter, applied after iteration consumes metadata.
#' @param policy Named list of explicit shared client choices; individual pagination arguments override it.
#' @noRd
.ct_request_paginated <- function(fn, ..., mode, parameter, size_parameter = NULL,
    page_size = NULL, start = NULL, items, max_pages = 100, max_items = NULL, next_cursor = NULL,
    completed = NULL, advance = NULL, stop_on_short = FALSE, error_policy = "stop",
    warn_limits = TRUE, format = NULL, policy = base::getOption(base::paste0(base::tolower(base::sub("_DRY_RUN$",
        "", "COMPTOXR_NATIVE_DRY_RUN")), "..ct_request.pagination"), base::list())) {
    allowed <- base::setdiff(base::names(base::formals(base::sys.function())), base::c("fn",
        "...", "policy"))
    if (!base::is.list(policy) || (base::length(policy) && (base::is.null(base::names(policy)) ||
        base::anyNA(base::names(policy)) || !base::all(base::nzchar(base::names(policy))) ||
        base::anyDuplicated(base::names(policy)) || !base::all(base::names(policy) %in%
        allowed)))) {
        base::stop("policy must be a named list of pagination defaults")
    }
    supplied <- base::names(base::match.call(expand.dots = FALSE))
    for (name in base::setdiff(base::names(policy), supplied)) {
        base::assign(name, policy[[name]])
    }
    for (value in base::list(completed, advance, format)) {
        if (!base::is.null(value) && !base::is.function(value)) {
            base::stop("Pagination callbacks must be functions")
        }
    }
    for (value in base::list(stop_on_short, warn_limits)) {
        if (!base::is.logical(value) || base::length(value) != 1L || base::is.na(value)) {
            base::stop("Pagination flags must be logical")
        }
    }
    if (!base::is.character(error_policy) || base::length(error_policy) != 1L ||
        base::is.na(error_policy) || !error_policy %in% base::c("stop", "partial",
        "empty")) {
        base::stop("error_policy must be stop, partial, or empty")
    }
    if (!base::is.function(fn) || !base::is.function(items)) {
        base::stop("fn and items must be functions")
    }
    if (!base::is.character(mode) || base::length(mode) != 1L || base::is.na(mode) ||
        !mode %in% base::c("page", "offset", "cursor")) {
        base::stop("mode must be page, offset, or cursor")
    }
    cursor <- mode == "cursor"
    if (cursor) {
        if (!base::is.function(next_cursor)) {
            base::stop("cursor mode requires next_cursor")
        }
        .ct_request_pagination_token(start)
        if (base::is.null(size_parameter) != base::is.null(page_size)) {
            base::stop("Supply size_parameter and page_size together")
        }
    }
    else if (base::is.null(size_parameter) || base::is.null(page_size) || base::is.null(start)) {
        base::stop("page/offset mode requires size_parameter, page_size, and start")
    }
    for (name in base::c(base::list(parameter), if (!base::is.null(size_parameter))
        base::list(size_parameter))) {
        if (!base::is.character(name) || !base::length(name) || base::anyNA(name) ||
            !base::all(base::nzchar(name))) {
            base::stop("pagination argument path must contain nonempty names")
        }
        if (!name[[1L]] %in% base::names(base::formals(fn)) && !"..." %in% base::names(base::formals(fn))) {
            base::stop("Unknown pagination argument: ", name)
        }
    }
    overlaps <- function(x, y) {
        !base::is.null(y) && base::identical(x[base::seq_len(base::min(base::length(x),
            base::length(y)))], y[base::seq_len(base::min(base::length(x), base::length(y)))])
    }
    if (overlaps(parameter, size_parameter)) {
        base::stop("Pagination arguments must be distinct")
    }
    numbers <- base::list(page_size = page_size, start = start, max_pages = max_pages,
        max_items = max_items)
    if (base::is.null(max_items)) {
        numbers$max_items <- NULL
    }
    if (cursor) {
        numbers$start <- NULL
    }
    if (cursor && base::is.null(page_size)) {
        numbers$page_size <- NULL
    }
    for (name in base::names(numbers)) {
        value <- numbers[[name]]
        if (!base::is.numeric(value) || base::length(value) != 1L || base::is.na(value) ||
            !base::is.finite(value) || value != base::floor(value) || value < (if (name ==
            "start")
            0
        else 1) || value > 2^53 - 1) {
            base::stop(name, " must be a finite integer within the supported range")
        }
    }
    step <- if (mode == "page")
        1
    else page_size
    if (!cursor && max_pages - 1 > (2^53 - 1 - start)/step) {
        base::stop("Pagination positions exceed the exact integer range")
    }
    args <- base::list(...)
    if (base::length(args) && (base::is.null(base::names(args)) || base::anyNA(base::names(args)) ||
        !base::all(base::nzchar(base::names(args))) || base::anyDuplicated(base::names(args)) ||
        base::any(base::names(args) %in% base::c(if (base::length(parameter) == 1L)
            parameter, if (base::length(size_parameter) == 1L)
            size_parameter)))) {
        base::stop("Fixed arguments must have unique names and exclude pagination arguments")
    }
    set_path <- function(x, path, value) {
        if (base::is.null(x)) {
            x <- base::list()
        }
        if (!base::is.list(x)) {
            base::stop("Nested pagination state must be a list")
        }
        key <- path[[1L]]
        if (base::length(path) == 1L) {
            x[key] <- base::list(value)
        }
        else {
            x[key] <- base::list(set_path(x[[key]], path[-1L], value))
        }
        x
    }
    args <- set_path(args, parameter, start)
    if (!base::is.null(size_parameter)) {
        args <- set_path(args, size_parameter, page_size)
    }
    item_limit <- if (base::is.null(max_items))
        Inf
    else max_items
    pages <- base::list()
    count <- 0
    requests <- 0
    position <- start
    seen <- base::new.env(hash = TRUE, parent = base::emptyenv())
    if (cursor && !base::is.null(start) && base::nzchar(start)) {
        seen[[digest::digest(start, algo = "sha256")]] <- TRUE
    }
    repeat {
        args <- set_path(args, parameter, position)
        if (!base::is.null(size_parameter)) {
            args <- set_path(args, size_parameter, page_size)
        }
        requests <- requests + 1
        response <- base::tryCatch(base::do.call(fn, args), error = function(e) {
            if (error_policy == "stop" || base::inherits(e, "pagination_security_error")) {
                base::stop(e)
            }
            e
        })
        if (base::inherits(response, "error")) {
            base::warning("Pagination request failed; returning ", error_policy,
                " results", call. = FALSE)
            if (error_policy == "empty") {
                pages <- base::list()
                count <- 0
            }
            reason <- "request_error"
            break
        }
        page <- items(response)
        if (base::is.null(page) || !(base::is.data.frame(page) || (base::is.null(base::dim(page)) &&
            (base::is.list(page) || base::is.atomic(page))))) {
            base::stop("items must return a list, atomic vector, or data frame")
        }
        n <- if (base::is.data.frame(page))
            base::nrow(page)
        else base::length(page)
        if (!n) {
            reason <- "empty_page"
            break
        }
        keep <- base::min(n, item_limit - count)
        pages[[base::length(pages) + 1L]] <- if (base::is.data.frame(page)) {
            page[base::seq_len(keep), , drop = FALSE]
        }
        else {
            page[base::seq_len(keep)]
        }
        count <- count + keep
        if (count == item_limit) {
            reason <- "max_items"
            if (warn_limits) {
                base::warning("Pagination truncated at ", reason, call. = FALSE)
            }
            break
        }
        if (!base::is.null(completed)) {
            done <- completed(response, base::list(position = position, requests = requests,
                item_count = count, page_size = page_size))
            if (!base::is.logical(done) || base::length(done) != 1L || base::is.na(done)) {
                base::stop("completed must return one nonmissing logical value")
            }
            if (done) {
                reason <- "completed"
                break
            }
        }
        if (stop_on_short && !base::is.null(page_size) && n < page_size) {
            reason <- "short_page"
            break
        }
        if (requests == max_pages) {
            reason <- "max_pages"
            if (warn_limits) {
                base::warning("Pagination truncated at ", reason, call. = FALSE)
            }
            break
        }
        if (cursor) {
            position <- next_cursor(response)
            .ct_request_pagination_token(position)
            if (base::is.null(position) || !base::nzchar(position)) {
                reason <- "no_next_cursor"
                break
            }
            key <- digest::digest(position, algo = "sha256")
            if (base::exists(key, envir = seen, inherits = FALSE)) {
                base::stop("Repeated pagination cursor or link")
            }
            seen[[key]] <- TRUE
        }
        else {
            next_position <- if (base::is.null(advance)) {
                position + step
            }
            else {
                advance(response, position, page_size)
            }
            if (!base::is.numeric(next_position) || base::length(next_position) !=
                1L || base::is.na(next_position) || !base::is.finite(next_position) ||
                next_position != base::floor(next_position) || next_position <= position ||
                next_position > 2^53 - 1) {
                base::stop("advance must return a larger exact integer position")
            }
            position <- next_position
        }
    }
    result <- base::list(pages = pages, requests = requests, item_count = count,
        stop_reason = reason)
    if (base::is.null(format))
        result
    else format(result)
}

.ct_request_pagination_token <- function(value) {
    if (!base::is.null(value) && (!base::is.character(value) || base::length(value) !=
        1L || base::is.na(value))) {
        base::stop("Pagination cursor or link must be NULL or a single non-missing string")
    }
    base::invisible(value)
}

#' Client-owned paginated_links companion
#' @param request A bodyless httr2 GET request with authentication and transport policy configured.
#' @param items Batch inputs, or an explicit response collection extractor for pagination.
#' @param next_link Explicit next-link extractor; defaults to the HTTP Link header.
#' @param max_pages Positive integer call bound, default 100.
#' @param max_items Optional positive integer retained-item bound; NULL means no item cap.
#' @param warn_limits Whether truncation warns, default TRUE in emitted companions.
#' @param error_policy Request error policy: stop by default, or explicit partial/empty recovery with warnings.
#' @param format Optional final-result formatter, applied after iteration consumes metadata.
#' @param policy Named list of explicit shared client choices; individual pagination arguments override it.
#' @noRd
.ct_request_paginated_links <- function(request, items, next_link = function(response) httr2::resp_link_url(response,
    "next"), max_pages = 100, max_items = NULL, warn_limits = TRUE, error_policy = "stop",
    format = NULL, policy = base::getOption(base::paste0(base::tolower(base::sub("_DRY_RUN$",
        "", "COMPTOXR_NATIVE_DRY_RUN")), "..ct_request.pagination_links"), base::list())) {
    if (base::missing(format) && base::is.list(policy)) {
        format <- policy$format
    }
    if (!base::is.null(format) && !base::is.function(format)) {
        base::stop("format must be a function")
    }
    if (!base::requireNamespace("httr2", quietly = TRUE) || utils::packageVersion("httr2") <
        "1.3.0") {
        base::stop("paginated_links requires httr2 >= 1.3.0")
    }
    if (!base::inherits(request, "httr2_request") || !base::is.function(next_link)) {
        base::stop("Supply an httr2 request and a next_link function")
    }
    if ((!base::is.null(request$method) && request$method != "GET") || !base::is.null(request$body)) {
        base::stop("Next-link pagination requires a bodyless GET request")
    }
    parse_url <- function(url, base_url = NULL) {
        .ct_request_pagination_token(url)
        if (base::is.null(url) || !base::nzchar(url) || base::grepl("[[:space:]\\\\]",
            url)) {
            base::stop("Invalid pagination URL")
        }
        parsed <- base::tryCatch(httr2::url_parse(url, base_url), error = function(e) {
            base::stop("Invalid pagination URL", call. = FALSE)
        })
        if (!parsed$scheme %in% base::c("http", "https") || base::is.null(parsed$hostname) ||
            !base::nzchar(parsed$hostname) || !base::is.null(parsed$username) ||
            !base::is.null(parsed$password) || !base::is.null(parsed$fragment)) {
            base::stop("Pagination URL must be HTTP(S) without userinfo or a fragment")
        }
        parsed
    }
    origin <- function(parsed) {
        base::list(base::tolower(parsed$scheme), base::tolower(parsed$hostname),
            base::as.character(if (!base::is.null(parsed$port)) {
                parsed$port
            }
            else if (parsed$scheme == "https") {
                443
            }
            else {
                80
            }))
    }
    initial <- parse_url(httr2::req_get_url(request))
    trusted <- origin(initial)
    checked_url <- function(url, base_url = NULL) {
        parsed <- parse_url(url, base_url)
        if (!base::identical(origin(parsed), trusted)) {
            base::stop("Cross-origin pagination link refused")
        }
        parsed$scheme <- base::tolower(parsed$scheme)
        parsed$hostname <- base::tolower(parsed$hostname)
        if (base::identical(base::as.character(parsed$port), if (parsed$scheme ==
            "https")
            "443"
        else "80")) {
            parsed$port <- NULL
        }
        httr2::url_build(parsed)
    }
    security_abort <- function(message) {
        base::stop(base::structure(base::list(message = message, call = NULL), class = base::c("pagination_security_error",
            "error", "condition")))
    }
    fetch <- function(url) {
        req <- httr2::req_url(request, checked_url(url))
        req <- httr2::req_options(req, followlocation = FALSE)
        response <- httr2::req_perform(req)
        if (httr2::resp_status(response) >= 300 && httr2::resp_status(response) <
            400) {
            security_abort("Pagination redirect refused")
        }
        httr2::resp_check_status(response)
        response
    }
    iteration <- base::list(fn = fetch, mode = "cursor", parameter = "url", start = checked_url(httr2::req_get_url(request)),
        items = items, next_cursor = function(response) {
            link <- next_link(response)
            .ct_request_pagination_token(link)
            if (base::is.null(link) || !base::nzchar(link)) {
                return(NULL)
            }
            checked_url(link, httr2::resp_url(response))
        }, policy = policy)
    for (name in base::c("max_pages", "max_items", "warn_limits", "error_policy")) {
        if (!name %in% base::names(policy) || name %in% base::names(base::match.call())) {
            iteration[name] <- base::list(base::get(name))
        }
    }
    iteration["format"] <- base::list(NULL)
    result <- base::do.call(.ct_request_paginated, iteration)
    if (result$stop_reason == "no_next_cursor") {
        result$stop_reason <- "no_next_link"
    }
    if (base::is.null(format))
        result
    else format(result)
}
