name: Clone Private Repository Workflow

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 6 * * *'
  pull_request:
  push:
  
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PAT_TO_PRIVATE }}
        src_path: /.
        dst_owner: seanthimons
        dst_repo_name: ComptoxR
