name: Release R Package

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R package dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build R package
        run: R CMD build .

      - name: List files for debugging
        run: ls -R

      - name: Get package version
        run: |
          VERSION=$(grep -m 1 '^Version:' DESCRIPTION | cut -d ' ' -f 2)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Find Package Asset
        id: find_package
        run: |
          # Find the full path to the built tarball
          PACKAGE_PATH=$(find . -maxdepth 2 -name "*.tar.gz" -type f | head -n 1)
          if [[ -z "$PACKAGE_PATH" ]]; then
            echo "Error: R package tarball (*.tar.gz) not found."
            exit 1
          fi
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
          echo "Found package at: $PACKAGE_PATH"

      # --- This single step now creates the release AND uploads the asset ---
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # This token MUST be a Personal Access Token with the 'repo' scope
          token: ${{ secrets.RELEASE_PAT }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: Release v${{ env.PACKAGE_VERSION }}
          body: |
            New release of the R package.
            Version: ${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
          # The 'files' parameter tells the action to upload the asset at this path
          files: ${{ env.PACKAGE_PATH }}

      # The separate 'actions/upload-release-asset' step has been removed.
