name: Release R Package

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R package dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Build R package
        run: R CMD build .

      # Add this step for debugging to see the file structure
      - name: List files to find package
        run: ls -R ..

      - name: Get package version
        id: get_version
        run: |
          VERSION=$(grep -m 1 '^Version:' DESCRIPTION | cut -d ' ' -f 2)
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV

      # New step to find the exact path of the built package
      - name: Find built package
        id: find_package
        run: |
          # The find command searches one level up for the tar.gz file
          # and saves the full path to an environment variable.
          PACKAGE_PATH=$(find .. -name "*.tar.gz" -type f)
          echo "PACKAGE_PATH=$PACKAGE_PATH" >> $GITHUB_ENV
          echo "Found package at: $PACKAGE_PATH"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_PAT }}
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: Release v${{ env.PACKAGE_VERSION }}
          body: |
            New release of the R package.
            Version: ${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false

      # Corrected upload step using the path we found
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Use the exact path found in the previous step
          asset_path: ${{ env.PACKAGE_PATH }}
          # Use the basename of the path for the asset name
          asset_name: ${{ basename(env.PACKAGE_PATH) }}
          asset_content_type: application/gzip
