name: Test Changelog Generation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-changelog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository with full history
      # fetch-depth: 0 is essential for the changelog builder to access all commits.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Generate the changelog
      # This step uses the same action as the release workflow to generate the notes.
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          # Using the default GITHUB_TOKEN is sufficient for reading repo history.
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Print the generated changelog to the logs
      # The output from the previous step is printed here for easy review.
      - name: Print Changelog
        run: |
          echo "--- Generated Changelog ---"
          echo "${{ steps.build_changelog.outputs.changelog }}"
          echo "---------------------------"
